
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  'NuxtImg': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  'NuxtPicture': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  'ElAffix': typeof import("../../node_modules/element-plus/es/components/affix/index")['ElAffix']
  'ElAlert': typeof import("../../node_modules/element-plus/es/components/alert/index")['ElAlert']
  'ElAnchor': typeof import("../../node_modules/element-plus/es/components/anchor/index")['ElAnchor']
  'ElAnchorLink': typeof import("../../node_modules/element-plus/es/components/anchor/index")['ElAnchorLink']
  'ElAutoResizer': typeof import("../../node_modules/element-plus/es/components/table-v2/index")['ElAutoResizer']
  'ElAside': typeof import("../../node_modules/element-plus/es/components/container/index")['ElAside']
  'ElAutocomplete': typeof import("../../node_modules/element-plus/es/components/autocomplete/index")['ElAutocomplete']
  'ElBacktop': typeof import("../../node_modules/element-plus/es/components/backtop/index")['ElBacktop']
  'ElAvatar': typeof import("../../node_modules/element-plus/es/components/avatar/index")['ElAvatar']
  'ElBreadcrumb': typeof import("../../node_modules/element-plus/es/components/breadcrumb/index")['ElBreadcrumb']
  'ElBreadcrumbItem': typeof import("../../node_modules/element-plus/es/components/breadcrumb/index")['ElBreadcrumbItem']
  'ElBadge': typeof import("../../node_modules/element-plus/es/components/badge/index")['ElBadge']
  'ElCalendar': typeof import("../../node_modules/element-plus/es/components/calendar/index")['ElCalendar']
  'ElButtonGroup': typeof import("../../node_modules/element-plus/es/components/button/index")['ElButtonGroup']
  'ElButton': typeof import("../../node_modules/element-plus/es/components/button/index")['ElButton']
  'ElCarousel': typeof import("../../node_modules/element-plus/es/components/carousel/index")['ElCarousel']
  'ElCarouselItem': typeof import("../../node_modules/element-plus/es/components/carousel/index")['ElCarouselItem']
  'ElCascader': typeof import("../../node_modules/element-plus/es/components/cascader/index")['ElCascader']
  'ElCheckTag': typeof import("../../node_modules/element-plus/es/components/check-tag/index")['ElCheckTag']
  'ElCascaderPanel': typeof import("../../node_modules/element-plus/es/components/cascader-panel/index")['ElCascaderPanel']
  'ElCheckbox': typeof import("../../node_modules/element-plus/es/components/checkbox/index")['ElCheckbox']
  'ElCheckboxGroup': typeof import("../../node_modules/element-plus/es/components/checkbox/index")['ElCheckboxGroup']
  'ElCheckboxButton': typeof import("../../node_modules/element-plus/es/components/checkbox/index")['ElCheckboxButton']
  'ElCard': typeof import("../../node_modules/element-plus/es/components/card/index")['ElCard']
  'ElCol': typeof import("../../node_modules/element-plus/es/components/col/index")['ElCol']
  'ElCollapse': typeof import("../../node_modules/element-plus/es/components/collapse/index")['ElCollapse']
  'ElColorPicker': typeof import("../../node_modules/element-plus/es/components/color-picker/index")['ElColorPicker']
  'ElCollapseTransition': typeof import("../../node_modules/element-plus/es/components/collapse-transition/index")['ElCollapseTransition']
  'ElColorPickerPanel': typeof import("../../node_modules/element-plus/es/components/color-picker-panel/index")['ElColorPickerPanel']
  'ElCollapseItem': typeof import("../../node_modules/element-plus/es/components/collapse/index")['ElCollapseItem']
  'ElContainer': typeof import("../../node_modules/element-plus/es/components/container/index")['ElContainer']
  'ElDatePicker': typeof import("../../node_modules/element-plus/es/components/date-picker/index")['ElDatePicker']
  'ElConfigProvider': typeof import("../../node_modules/element-plus/es/components/config-provider/index")['ElConfigProvider']
  'ElCountdown': typeof import("../../node_modules/element-plus/es/components/countdown/index")['ElCountdown']
  'ElDatePickerPanel': typeof import("../../node_modules/element-plus/es/components/date-picker-panel/index")['ElDatePickerPanel']
  'ElDialog': typeof import("../../node_modules/element-plus/es/components/dialog/index")['ElDialog']
  'ElDescriptions': typeof import("../../node_modules/element-plus/es/components/descriptions/index")['ElDescriptions']
  'ElDescriptionsItem': typeof import("../../node_modules/element-plus/es/components/descriptions/index")['ElDescriptionsItem']
  'ElDivider': typeof import("../../node_modules/element-plus/es/components/divider/index")['ElDivider']
  'ElDropdownItem': typeof import("../../node_modules/element-plus/es/components/dropdown/index")['ElDropdownItem']
  'ElDrawer': typeof import("../../node_modules/element-plus/es/components/drawer/index")['ElDrawer']
  'ElForm': typeof import("../../node_modules/element-plus/es/components/form/index")['ElForm']
  'ElDropdown': typeof import("../../node_modules/element-plus/es/components/dropdown/index")['ElDropdown']
  'ElFooter': typeof import("../../node_modules/element-plus/es/components/container/index")['ElFooter']
  'ElEmpty': typeof import("../../node_modules/element-plus/es/components/empty/index")['ElEmpty']
  'ElFormItem': typeof import("../../node_modules/element-plus/es/components/form/index")['ElFormItem']
  'ElDropdownMenu': typeof import("../../node_modules/element-plus/es/components/dropdown/index")['ElDropdownMenu']
  'ElHeader': typeof import("../../node_modules/element-plus/es/components/container/index")['ElHeader']
  'ElIcon': typeof import("../../node_modules/element-plus/es/components/icon/index")['ElIcon']
  'ElImage': typeof import("../../node_modules/element-plus/es/components/image/index")['ElImage']
  'ElInput': typeof import("../../node_modules/element-plus/es/components/input/index")['ElInput']
  'ElInputNumber': typeof import("../../node_modules/element-plus/es/components/input-number/index")['ElInputNumber']
  'ElInputTag': typeof import("../../node_modules/element-plus/es/components/input-tag/index")['ElInputTag']
  'ElImageViewer': typeof import("../../node_modules/element-plus/es/components/image-viewer/index")['ElImageViewer']
  'ElLink': typeof import("../../node_modules/element-plus/es/components/link/index")['ElLink']
  'ElMain': typeof import("../../node_modules/element-plus/es/components/container/index")['ElMain']
  'ElMenu': typeof import("../../node_modules/element-plus/es/components/menu/index")['ElMenu']
  'ElMention': typeof import("../../node_modules/element-plus/es/components/mention/index")['ElMention']
  'ElMenuItem': typeof import("../../node_modules/element-plus/es/components/menu/index")['ElMenuItem']
  'ElPopover': typeof import("../../node_modules/element-plus/es/components/popover/index")['ElPopover']
  'ElPagination': typeof import("../../node_modules/element-plus/es/components/pagination/index")['ElPagination']
  'ElPopper': typeof import("../../node_modules/element-plus/es/components/popper/index")['ElPopper']
  'ElPopperContent': typeof import("../../node_modules/element-plus/es/components/popper/index")['ElPopperContent']
  'ElPopperArrow': typeof import("../../node_modules/element-plus/es/components/popper/index")['ElPopperArrow']
  'ElPopperTrigger': typeof import("../../node_modules/element-plus/es/components/popper/index")['ElPopperTrigger']
  'ElProgress': typeof import("../../node_modules/element-plus/es/components/progress/index")['ElProgress']
  'ElRadio': typeof import("../../node_modules/element-plus/es/components/radio/index")['ElRadio']
  'ElRadioButton': typeof import("../../node_modules/element-plus/es/components/radio/index")['ElRadioButton']
  'ElRadioGroup': typeof import("../../node_modules/element-plus/es/components/radio/index")['ElRadioGroup']
  'ElRate': typeof import("../../node_modules/element-plus/es/components/rate/index")['ElRate']
  'ElResult': typeof import("../../node_modules/element-plus/es/components/result/index")['ElResult']
  'ElRow': typeof import("../../node_modules/element-plus/es/components/row/index")['ElRow']
  'ElScrollbar': typeof import("../../node_modules/element-plus/es/components/scrollbar/index")['ElScrollbar']
  'ElSegmented': typeof import("../../node_modules/element-plus/es/components/segmented/index")['ElSegmented']
  'ElSelectV2': typeof import("../../node_modules/element-plus/es/components/select-v2/index")['ElSelectV2']
  'ElSelect': typeof import("../../node_modules/element-plus/es/components/select/index")['ElSelect']
  'ElSkeleton': typeof import("../../node_modules/element-plus/es/components/skeleton/index")['ElSkeleton']
  'ElSkeletonItem': typeof import("../../node_modules/element-plus/es/components/skeleton/index")['ElSkeletonItem']
  'ElSlider': typeof import("../../node_modules/element-plus/es/components/slider/index")['ElSlider']
  'ElSpace': typeof import("../../node_modules/element-plus/es/components/space/index")['ElSpace']
  'ElSplitter': typeof import("../../node_modules/element-plus/es/components/splitter/index")['ElSplitter']
  'ElSplitterPanel': typeof import("../../node_modules/element-plus/es/components/splitter/index")['ElSplitterPanel']
  'ElStep': typeof import("../../node_modules/element-plus/es/components/steps/index")['ElStep']
  'ElStatistic': typeof import("../../node_modules/element-plus/es/components/statistic/index")['ElStatistic']
  'ElSteps': typeof import("../../node_modules/element-plus/es/components/steps/index")['ElSteps']
  'ElSubMenu': typeof import("../../node_modules/element-plus/es/components/menu/index")['ElSubMenu']
  'ElSwitch': typeof import("../../node_modules/element-plus/es/components/switch/index")['ElSwitch']
  'ElTabPane': typeof import("../../node_modules/element-plus/es/components/tabs/index")['ElTabPane']
  'ElTable': typeof import("../../node_modules/element-plus/es/components/table/index")['ElTable']
  'ElTableColumn': typeof import("../../node_modules/element-plus/es/components/table/index")['ElTableColumn']
  'ElMenuItemGroup': typeof import("../../node_modules/element-plus/es/components/menu/index")['ElMenuItemGroup']
  'ElTableV2': typeof import("../../node_modules/element-plus/es/components/table-v2/index")['ElTableV2']
  'ElTabs': typeof import("../../node_modules/element-plus/es/components/tabs/index")['ElTabs']
  'ElTag': typeof import("../../node_modules/element-plus/es/components/tag/index")['ElTag']
  'ElOption': typeof import("../../node_modules/element-plus/es/components/select/index")['ElOption']
  'ElTimeSelect': typeof import("../../node_modules/element-plus/es/components/time-select/index")['ElTimeSelect']
  'ElOverlay': typeof import("../../node_modules/element-plus/es/components/overlay/index")['ElOverlay']
  'ElTimeline': typeof import("../../node_modules/element-plus/es/components/timeline/index")['ElTimeline']
  'ElOptionGroup': typeof import("../../node_modules/element-plus/es/components/select/index")['ElOptionGroup']
  'ElPageHeader': typeof import("../../node_modules/element-plus/es/components/page-header/index")['ElPageHeader']
  'ElTooltip': typeof import("../../node_modules/element-plus/es/components/tooltip/index")['ElTooltip']
  'ElTimelineItem': typeof import("../../node_modules/element-plus/es/components/timeline/index")['ElTimelineItem']
  'ElTour': typeof import("../../node_modules/element-plus/es/components/tour/index")['ElTour']
  'ElTransfer': typeof import("../../node_modules/element-plus/es/components/transfer/index")['ElTransfer']
  'ElTourStep': typeof import("../../node_modules/element-plus/es/components/tour/index")['ElTourStep']
  'ElTree': typeof import("../../node_modules/element-plus/es/components/tree/index")['ElTree']
  'ElIconAddLocation': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['AddLocation']
  'ElTreeV2': typeof import("../../node_modules/element-plus/es/components/tree-v2/index")['ElTreeV2']
  'ElIconAim': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Aim']
  'ElTreeSelect': typeof import("../../node_modules/element-plus/es/components/tree-select/index")['ElTreeSelect']
  'ElUpload': typeof import("../../node_modules/element-plus/es/components/upload/index")['ElUpload']
  'ElIconAlarmClock': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['AlarmClock']
  'ElIconArrowDown': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowDown']
  'ElIconArrowDownBold': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowDownBold']
  'ElIconApple': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Apple']
  'ElIconArrowLeft': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowLeft']
  'ElIconArrowRight': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowRight']
  'ElIconArrowUp': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowUp']
  'ElIconArrowLeftBold': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowLeftBold']
  'ElIconArrowRightBold': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowRightBold']
  'ElIconAvatar': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Avatar']
  'ElIconBack': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Back']
  'ElIconArrowUpBold': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowUpBold']
  'ElTimePicker': typeof import("../../node_modules/element-plus/es/components/time-picker/index")['ElTimePicker']
  'ElIconBasketball': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Basketball']
  'ElIconBaseball': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Baseball']
  'ElIconBell': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Bell']
  'ElText': typeof import("../../node_modules/element-plus/es/components/text/index")['ElText']
  'ElIconBellFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['BellFilled']
  'ElIconBottom': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Bottom']
  'ElWatermark': typeof import("../../node_modules/element-plus/es/components/watermark/index")['ElWatermark']
  'ElPopconfirm': typeof import("../../node_modules/element-plus/es/components/popconfirm/index")['ElPopconfirm']
  'ElIconBicycle': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Bicycle']
  'ElIconBox': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Box']
  'ElIconBottomLeft': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['BottomLeft']
  'ElIconBrush': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Brush']
  'ElIconCalendar': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Calendar']
  'ElIconBriefcase': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Briefcase']
  'ElIconCamera': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Camera']
  'ElIconBrushFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['BrushFilled']
  'ElIconCaretLeft': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CaretLeft']
  'ElIconCaretBottom': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CaretBottom']
  'ElIconCaretTop': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CaretTop']
  'ElIconCaretRight': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CaretRight']
  'ElIconCameraFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CameraFilled']
  'ElIconCellphone': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Cellphone']
  'ElIconChatDotRound': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChatDotRound']
  'ElIconBottomRight': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['BottomRight']
  'ElIconChatLineRound': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChatLineRound']
  'ElIconBowl': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Bowl']
  'ElIconBurger': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Burger']
  'ElIconChatLineSquare': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChatLineSquare']
  'ElIconChatRound': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChatRound']
  'ElIconChecked': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Checked']
  'ElIconCheck': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Check']
  'ElIconChatDotSquare': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChatDotSquare']
  'ElIconCherry': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Cherry']
  'ElIconCircleCheck': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CircleCheck']
  'ElIconChromeFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChromeFilled']
  'ElIconChatSquare': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChatSquare']
  'ElIconCirclePlusFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CirclePlusFilled']
  'ElIconChicken': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Chicken']
  'ElIconCircleCloseFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CircleCloseFilled']
  'ElIconCloudy': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Cloudy']
  'ElIconClock': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Clock']
  'ElIconClose': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Close']
  'ElIconCloseBold': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CloseBold']
  'ElIconCoffee': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Coffee']
  'ElIconCoffeeCup': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CoffeeCup']
  'ElIconCoin': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Coin']
  'ElIconColdDrink': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ColdDrink']
  'ElIconCollectionTag': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CollectionTag']
  'ElIconCompass': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Compass']
  'ElIconCollection': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Collection']
  'ElIconComment': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Comment']
  'ElIconConnection': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Connection']
  'ElIconCopyDocument': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CopyDocument']
  'ElIconCoordinate': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Coordinate']
  'ElIconCircleCheckFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CircleCheckFilled']
  'ElIconCircleClose': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CircleClose']
  'ElIconCirclePlus': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CirclePlus']
  'ElIconCreditCard': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CreditCard']
  'ElIconCpu': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Cpu']
  'ElIconDArrowRight': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DArrowRight']
  'ElIconCrop': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Crop']
  'ElIconDCaret': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DCaret']
  'ElIconDelete': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Delete']
  'ElIconDataBoard': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DataBoard']
  'ElIconDataLine': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DataLine']
  'ElIconDArrowLeft': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DArrowLeft']
  'ElIconDataAnalysis': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DataAnalysis']
  'ElIconDeleteFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DeleteFilled']
  'ElIconDiscount': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Discount']
  'ElIconDessert': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Dessert']
  'ElIconDeleteLocation': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DeleteLocation']
  'ElIconDishDot': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DishDot']
  'ElIconDish': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Dish']
  'ElIconDocument': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Document']
  'ElIconDocumentAdd': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DocumentAdd']
  'ElIconDocumentChecked': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DocumentChecked']
  'ElIconDocumentCopy': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DocumentCopy']
  'ElIconDocumentDelete': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DocumentDelete']
  'ElIconDocumentRemove': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DocumentRemove']
  'ElIconDownload': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Download']
  'ElIconDrizzling': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Drizzling']
  'ElIconEdit': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Edit']
  'ElIconEditPen': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['EditPen']
  'ElIconEleme': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Eleme']
  'ElIconElementPlus': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ElementPlus']
  'ElIconElemeFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ElemeFilled']
  'ElIconFailed': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Failed']
  'ElIconFemale': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Female']
  'ElIconExpand': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Expand']
  'ElIconFilter': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Filter']
  'ElIconFinished': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Finished']
  'ElIconFilm': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Film']
  'ElIconFiles': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Files']
  'ElIconFirstAidKit': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FirstAidKit']
  'ElIconFold': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Fold']
  'ElIconFlag': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Flag']
  'ElIconFolderAdd': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FolderAdd']
  'ElIconFolderChecked': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FolderChecked']
  'ElIconFolderDelete': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FolderDelete']
  'ElIconFolderOpened': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FolderOpened']
  'ElIconFolder': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Folder']
  'ElIconFolderRemove': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FolderRemove']
  'ElIconFood': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Food']
  'ElIconFootball': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Football']
  'ElIconForkSpoon': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ForkSpoon']
  'ElIconFries': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Fries']
  'ElIconFullScreen': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FullScreen']
  'ElIconGoblet': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Goblet']
  'ElIconGobletFull': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['GobletFull']
  'ElIconGobletSquare': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['GobletSquare']
  'ElIconGobletSquareFull': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['GobletSquareFull']
  'ElIconGoldMedal': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['GoldMedal']
  'ElIconGoodsFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['GoodsFilled']
  'ElIconGrape': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Grape']
  'ElIconGoods': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Goods']
  'ElIconGrid': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Grid']
  'ElIconHandbag': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Handbag']
  'ElIconGuide': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Guide']
  'ElIconHeadset': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Headset']
  'ElIconHelp': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Help']
  'ElIconHide': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Hide']
  'ElIconHelpFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['HelpFilled']
  'ElIconHistogram': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Histogram']
  'ElIconHomeFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['HomeFilled']
  'ElIconHouse': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['House']
  'ElIconHotWater': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['HotWater']
  'ElIconIceCream': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['IceCream']
  'ElIconIceCreamSquare': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['IceCreamSquare']
  'ElIconIceCreamRound': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['IceCreamRound']
  'ElIconIceDrink': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['IceDrink']
  'ElIconIceTea': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['IceTea']
  'ElIconInfoFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['InfoFilled']
  'ElIconIphone': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Iphone']
  'ElIconKey': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Key']
  'ElIconKnifeFork': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['KnifeFork']
  'ElIconLightning': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Lightning']
  'ElIconList': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['List']
  'ElIconLink': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Link']
  'ElIconLoading': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Loading']
  'ElIconLocation': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Location']
  'ElIconLocationFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['LocationFilled']
  'ElIconLocationInformation': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['LocationInformation']
  'ElIconLock': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Lock']
  'ElIconLollipop': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Lollipop']
  'ElIconMagicStick': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MagicStick']
  'ElIconMagnet': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Magnet']
  'ElIconMale': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Male']
  'ElIconManagement': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Management']
  'ElIconMapLocation': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MapLocation']
  'ElIconMedal': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Medal']
  'ElIconMemo': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Memo']
  'ElIconMenu': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Menu']
  'ElIconMessage': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Message']
  'ElIconMessageBox': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MessageBox']
  'ElIconMic': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Mic']
  'ElIconMicrophone': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Microphone']
  'ElIconMilkTea': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MilkTea']
  'ElIconMinus': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Minus']
  'ElIconMonitor': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Monitor']
  'ElIconMoney': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Money']
  'ElIconMoon': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Moon']
  'ElIconMoonNight': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MoonNight']
  'ElIconMore': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['More']
  'ElIconMostlyCloudy': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MostlyCloudy']
  'ElIconMouse': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Mouse']
  'ElIconMoreFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MoreFilled']
  'ElIconMute': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Mute']
  'ElIconMuteNotification': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MuteNotification']
  'ElIconMug': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Mug']
  'ElIconNoSmoking': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['NoSmoking']
  'ElIconNotebook': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Notebook']
  'ElIconOfficeBuilding': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['OfficeBuilding']
  'ElIconNotification': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Notification']
  'ElIconOdometer': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Odometer']
  'ElIconOpen': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Open']
  'ElIconOpportunity': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Opportunity']
  'ElIconOperation': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Operation']
  'ElIconOrange': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Orange']
  'ElIconPaperclip': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Paperclip']
  'ElIconPear': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Pear']
  'ElIconPhone': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Phone']
  'ElIconPhoneFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['PhoneFilled']
  'ElIconPicture': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Picture']
  'ElIconPictureFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['PictureFilled']
  'ElIconPictureRounded': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['PictureRounded']
  'ElIconPieChart': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['PieChart']
  'ElIconPlace': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Place']
  'ElIconPartlyCloudy': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['PartlyCloudy']
  'ElIconPlatform': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Platform']
  'ElIconPlus': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Plus']
  'ElIconPointer': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Pointer']
  'ElIconPosition': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Position']
  'ElIconPostcard': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Postcard']
  'ElIconPresent': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Present']
  'ElIconPrinter': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Printer']
  'ElIconPouring': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Pouring']
  'ElIconQuartzWatch': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['QuartzWatch']
  'ElIconRank': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Rank']
  'ElIconQuestionFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['QuestionFilled']
  'ElIconPromotion': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Promotion']
  'ElIconPriceTag': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['PriceTag']
  'ElIconReading': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Reading']
  'ElIconRefresh': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Refresh']
  'ElIconRefreshLeft': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['RefreshLeft']
  'ElIconRefrigerator': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Refrigerator']
  'ElIconRemove': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Remove']
  'ElIconRefreshRight': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['RefreshRight']
  'ElIconRight': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Right']
  'ElIconReadingLamp': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ReadingLamp']
  'ElIconSchool': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['School']
  'ElIconRemoveFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['RemoveFilled']
  'ElIconScissor': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Scissor']
  'ElIconSelect': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Select']
  'ElIconScaleToOriginal': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ScaleToOriginal']
  'ElIconSell': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Sell']
  'ElIconSearch': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Search']
  'ElIconSetUp': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SetUp']
  'ElIconSemiSelect': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SemiSelect']
  'ElIconService': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Service']
  'ElIconShare': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Share']
  'ElIconSetting': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Setting']
  'ElIconShip': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Ship']
  'ElIconShoppingCart': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ShoppingCart']
  'ElIconShop': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Shop']
  'ElIconShoppingBag': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ShoppingBag']
  'ElIconShoppingCartFull': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ShoppingCartFull']
  'ElIconShoppingTrolley': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ShoppingTrolley']
  'ElIconSoldOut': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SoldOut']
  'ElIconSmoking': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Smoking']
  'ElIconSoccer': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Soccer']
  'ElIconSort': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Sort']
  'ElIconSortDown': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SortDown']
  'ElIconStar': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Star']
  'ElIconStarFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['StarFilled']
  'ElIconSortUp': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SortUp']
  'ElIconStopwatch': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Stopwatch']
  'ElIconSuitcase': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Suitcase']
  'ElIconSuccessFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SuccessFilled']
  'ElIconSugar': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Sugar']
  'ElIconSunny': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Sunny']
  'ElIconSunset': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Sunset']
  'ElIconSwitch': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Switch']
  'ElIconSuitcaseLine': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SuitcaseLine']
  'ElIconSunrise': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Sunrise']
  'ElIconSwitchButton': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SwitchButton']
  'ElIconTicket': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Ticket']
  'ElIconSwitchFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SwitchFilled']
  'ElIconTimer': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Timer']
  'ElIconTakeawayBox': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['TakeawayBox']
  'ElIconTools': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Tools']
  'ElIconTop': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Top']
  'ElIconTopLeft': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['TopLeft']
  'ElIconTopRight': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['TopRight']
  'ElIconTickets': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Tickets']
  'ElIconToiletPaper': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ToiletPaper']
  'ElIconTrophyBase': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['TrophyBase']
  'ElIconTurnOff': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['TurnOff']
  'ElIconUmbrella': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Umbrella']
  'ElIconTrendCharts': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['TrendCharts']
  'ElIconUpload': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Upload']
  'ElIconTrophy': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Trophy']
  'ElIconUnlock': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Unlock']
  'ElIconUploadFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['UploadFilled']
  'ElIconStamp': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Stamp']
  'ElIconUser': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['User']
  'ElIconUserFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['UserFilled']
  'ElIconVan': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Van']
  'ElIconVideoCamera': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['VideoCamera']
  'ElIconVideoCameraFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['VideoCameraFilled']
  'ElIconVideoPause': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['VideoPause']
  'ElIconVideoPlay': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['VideoPlay']
  'ElIconView': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['View']
  'ElIconWalletFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['WalletFilled']
  'ElIconWallet': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Wallet']
  'ElIconWarning': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Warning']
  'ElIconWarnTriangleFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['WarnTriangleFilled']
  'ElIconWatermelon': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Watermelon']
  'ElIconWatch': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Watch']
  'ElIconZoomIn': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ZoomIn']
  'ElIconWarningFilled': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['WarningFilled']
  'ElIconWindPower': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['WindPower']
  'ElIconZoomOut': typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ZoomOut']
  'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  'LazyElAffix': LazyComponent<typeof import("../../node_modules/element-plus/es/components/affix/index")['ElAffix']>
  'LazyElAlert': LazyComponent<typeof import("../../node_modules/element-plus/es/components/alert/index")['ElAlert']>
  'LazyElAnchor': LazyComponent<typeof import("../../node_modules/element-plus/es/components/anchor/index")['ElAnchor']>
  'LazyElAnchorLink': LazyComponent<typeof import("../../node_modules/element-plus/es/components/anchor/index")['ElAnchorLink']>
  'LazyElAutoResizer': LazyComponent<typeof import("../../node_modules/element-plus/es/components/table-v2/index")['ElAutoResizer']>
  'LazyElAside': LazyComponent<typeof import("../../node_modules/element-plus/es/components/container/index")['ElAside']>
  'LazyElAutocomplete': LazyComponent<typeof import("../../node_modules/element-plus/es/components/autocomplete/index")['ElAutocomplete']>
  'LazyElBacktop': LazyComponent<typeof import("../../node_modules/element-plus/es/components/backtop/index")['ElBacktop']>
  'LazyElAvatar': LazyComponent<typeof import("../../node_modules/element-plus/es/components/avatar/index")['ElAvatar']>
  'LazyElBreadcrumb': LazyComponent<typeof import("../../node_modules/element-plus/es/components/breadcrumb/index")['ElBreadcrumb']>
  'LazyElBreadcrumbItem': LazyComponent<typeof import("../../node_modules/element-plus/es/components/breadcrumb/index")['ElBreadcrumbItem']>
  'LazyElBadge': LazyComponent<typeof import("../../node_modules/element-plus/es/components/badge/index")['ElBadge']>
  'LazyElCalendar': LazyComponent<typeof import("../../node_modules/element-plus/es/components/calendar/index")['ElCalendar']>
  'LazyElButtonGroup': LazyComponent<typeof import("../../node_modules/element-plus/es/components/button/index")['ElButtonGroup']>
  'LazyElButton': LazyComponent<typeof import("../../node_modules/element-plus/es/components/button/index")['ElButton']>
  'LazyElCarousel': LazyComponent<typeof import("../../node_modules/element-plus/es/components/carousel/index")['ElCarousel']>
  'LazyElCarouselItem': LazyComponent<typeof import("../../node_modules/element-plus/es/components/carousel/index")['ElCarouselItem']>
  'LazyElCascader': LazyComponent<typeof import("../../node_modules/element-plus/es/components/cascader/index")['ElCascader']>
  'LazyElCheckTag': LazyComponent<typeof import("../../node_modules/element-plus/es/components/check-tag/index")['ElCheckTag']>
  'LazyElCascaderPanel': LazyComponent<typeof import("../../node_modules/element-plus/es/components/cascader-panel/index")['ElCascaderPanel']>
  'LazyElCheckbox': LazyComponent<typeof import("../../node_modules/element-plus/es/components/checkbox/index")['ElCheckbox']>
  'LazyElCheckboxGroup': LazyComponent<typeof import("../../node_modules/element-plus/es/components/checkbox/index")['ElCheckboxGroup']>
  'LazyElCheckboxButton': LazyComponent<typeof import("../../node_modules/element-plus/es/components/checkbox/index")['ElCheckboxButton']>
  'LazyElCard': LazyComponent<typeof import("../../node_modules/element-plus/es/components/card/index")['ElCard']>
  'LazyElCol': LazyComponent<typeof import("../../node_modules/element-plus/es/components/col/index")['ElCol']>
  'LazyElCollapse': LazyComponent<typeof import("../../node_modules/element-plus/es/components/collapse/index")['ElCollapse']>
  'LazyElColorPicker': LazyComponent<typeof import("../../node_modules/element-plus/es/components/color-picker/index")['ElColorPicker']>
  'LazyElCollapseTransition': LazyComponent<typeof import("../../node_modules/element-plus/es/components/collapse-transition/index")['ElCollapseTransition']>
  'LazyElColorPickerPanel': LazyComponent<typeof import("../../node_modules/element-plus/es/components/color-picker-panel/index")['ElColorPickerPanel']>
  'LazyElCollapseItem': LazyComponent<typeof import("../../node_modules/element-plus/es/components/collapse/index")['ElCollapseItem']>
  'LazyElContainer': LazyComponent<typeof import("../../node_modules/element-plus/es/components/container/index")['ElContainer']>
  'LazyElDatePicker': LazyComponent<typeof import("../../node_modules/element-plus/es/components/date-picker/index")['ElDatePicker']>
  'LazyElConfigProvider': LazyComponent<typeof import("../../node_modules/element-plus/es/components/config-provider/index")['ElConfigProvider']>
  'LazyElCountdown': LazyComponent<typeof import("../../node_modules/element-plus/es/components/countdown/index")['ElCountdown']>
  'LazyElDatePickerPanel': LazyComponent<typeof import("../../node_modules/element-plus/es/components/date-picker-panel/index")['ElDatePickerPanel']>
  'LazyElDialog': LazyComponent<typeof import("../../node_modules/element-plus/es/components/dialog/index")['ElDialog']>
  'LazyElDescriptions': LazyComponent<typeof import("../../node_modules/element-plus/es/components/descriptions/index")['ElDescriptions']>
  'LazyElDescriptionsItem': LazyComponent<typeof import("../../node_modules/element-plus/es/components/descriptions/index")['ElDescriptionsItem']>
  'LazyElDivider': LazyComponent<typeof import("../../node_modules/element-plus/es/components/divider/index")['ElDivider']>
  'LazyElDropdownItem': LazyComponent<typeof import("../../node_modules/element-plus/es/components/dropdown/index")['ElDropdownItem']>
  'LazyElDrawer': LazyComponent<typeof import("../../node_modules/element-plus/es/components/drawer/index")['ElDrawer']>
  'LazyElForm': LazyComponent<typeof import("../../node_modules/element-plus/es/components/form/index")['ElForm']>
  'LazyElDropdown': LazyComponent<typeof import("../../node_modules/element-plus/es/components/dropdown/index")['ElDropdown']>
  'LazyElFooter': LazyComponent<typeof import("../../node_modules/element-plus/es/components/container/index")['ElFooter']>
  'LazyElEmpty': LazyComponent<typeof import("../../node_modules/element-plus/es/components/empty/index")['ElEmpty']>
  'LazyElFormItem': LazyComponent<typeof import("../../node_modules/element-plus/es/components/form/index")['ElFormItem']>
  'LazyElDropdownMenu': LazyComponent<typeof import("../../node_modules/element-plus/es/components/dropdown/index")['ElDropdownMenu']>
  'LazyElHeader': LazyComponent<typeof import("../../node_modules/element-plus/es/components/container/index")['ElHeader']>
  'LazyElIcon': LazyComponent<typeof import("../../node_modules/element-plus/es/components/icon/index")['ElIcon']>
  'LazyElImage': LazyComponent<typeof import("../../node_modules/element-plus/es/components/image/index")['ElImage']>
  'LazyElInput': LazyComponent<typeof import("../../node_modules/element-plus/es/components/input/index")['ElInput']>
  'LazyElInputNumber': LazyComponent<typeof import("../../node_modules/element-plus/es/components/input-number/index")['ElInputNumber']>
  'LazyElInputTag': LazyComponent<typeof import("../../node_modules/element-plus/es/components/input-tag/index")['ElInputTag']>
  'LazyElImageViewer': LazyComponent<typeof import("../../node_modules/element-plus/es/components/image-viewer/index")['ElImageViewer']>
  'LazyElLink': LazyComponent<typeof import("../../node_modules/element-plus/es/components/link/index")['ElLink']>
  'LazyElMain': LazyComponent<typeof import("../../node_modules/element-plus/es/components/container/index")['ElMain']>
  'LazyElMenu': LazyComponent<typeof import("../../node_modules/element-plus/es/components/menu/index")['ElMenu']>
  'LazyElMention': LazyComponent<typeof import("../../node_modules/element-plus/es/components/mention/index")['ElMention']>
  'LazyElMenuItem': LazyComponent<typeof import("../../node_modules/element-plus/es/components/menu/index")['ElMenuItem']>
  'LazyElPopover': LazyComponent<typeof import("../../node_modules/element-plus/es/components/popover/index")['ElPopover']>
  'LazyElPagination': LazyComponent<typeof import("../../node_modules/element-plus/es/components/pagination/index")['ElPagination']>
  'LazyElPopper': LazyComponent<typeof import("../../node_modules/element-plus/es/components/popper/index")['ElPopper']>
  'LazyElPopperContent': LazyComponent<typeof import("../../node_modules/element-plus/es/components/popper/index")['ElPopperContent']>
  'LazyElPopperArrow': LazyComponent<typeof import("../../node_modules/element-plus/es/components/popper/index")['ElPopperArrow']>
  'LazyElPopperTrigger': LazyComponent<typeof import("../../node_modules/element-plus/es/components/popper/index")['ElPopperTrigger']>
  'LazyElProgress': LazyComponent<typeof import("../../node_modules/element-plus/es/components/progress/index")['ElProgress']>
  'LazyElRadio': LazyComponent<typeof import("../../node_modules/element-plus/es/components/radio/index")['ElRadio']>
  'LazyElRadioButton': LazyComponent<typeof import("../../node_modules/element-plus/es/components/radio/index")['ElRadioButton']>
  'LazyElRadioGroup': LazyComponent<typeof import("../../node_modules/element-plus/es/components/radio/index")['ElRadioGroup']>
  'LazyElRate': LazyComponent<typeof import("../../node_modules/element-plus/es/components/rate/index")['ElRate']>
  'LazyElResult': LazyComponent<typeof import("../../node_modules/element-plus/es/components/result/index")['ElResult']>
  'LazyElRow': LazyComponent<typeof import("../../node_modules/element-plus/es/components/row/index")['ElRow']>
  'LazyElScrollbar': LazyComponent<typeof import("../../node_modules/element-plus/es/components/scrollbar/index")['ElScrollbar']>
  'LazyElSegmented': LazyComponent<typeof import("../../node_modules/element-plus/es/components/segmented/index")['ElSegmented']>
  'LazyElSelectV2': LazyComponent<typeof import("../../node_modules/element-plus/es/components/select-v2/index")['ElSelectV2']>
  'LazyElSelect': LazyComponent<typeof import("../../node_modules/element-plus/es/components/select/index")['ElSelect']>
  'LazyElSkeleton': LazyComponent<typeof import("../../node_modules/element-plus/es/components/skeleton/index")['ElSkeleton']>
  'LazyElSkeletonItem': LazyComponent<typeof import("../../node_modules/element-plus/es/components/skeleton/index")['ElSkeletonItem']>
  'LazyElSlider': LazyComponent<typeof import("../../node_modules/element-plus/es/components/slider/index")['ElSlider']>
  'LazyElSpace': LazyComponent<typeof import("../../node_modules/element-plus/es/components/space/index")['ElSpace']>
  'LazyElSplitter': LazyComponent<typeof import("../../node_modules/element-plus/es/components/splitter/index")['ElSplitter']>
  'LazyElSplitterPanel': LazyComponent<typeof import("../../node_modules/element-plus/es/components/splitter/index")['ElSplitterPanel']>
  'LazyElStep': LazyComponent<typeof import("../../node_modules/element-plus/es/components/steps/index")['ElStep']>
  'LazyElStatistic': LazyComponent<typeof import("../../node_modules/element-plus/es/components/statistic/index")['ElStatistic']>
  'LazyElSteps': LazyComponent<typeof import("../../node_modules/element-plus/es/components/steps/index")['ElSteps']>
  'LazyElSubMenu': LazyComponent<typeof import("../../node_modules/element-plus/es/components/menu/index")['ElSubMenu']>
  'LazyElSwitch': LazyComponent<typeof import("../../node_modules/element-plus/es/components/switch/index")['ElSwitch']>
  'LazyElTabPane': LazyComponent<typeof import("../../node_modules/element-plus/es/components/tabs/index")['ElTabPane']>
  'LazyElTable': LazyComponent<typeof import("../../node_modules/element-plus/es/components/table/index")['ElTable']>
  'LazyElTableColumn': LazyComponent<typeof import("../../node_modules/element-plus/es/components/table/index")['ElTableColumn']>
  'LazyElMenuItemGroup': LazyComponent<typeof import("../../node_modules/element-plus/es/components/menu/index")['ElMenuItemGroup']>
  'LazyElTableV2': LazyComponent<typeof import("../../node_modules/element-plus/es/components/table-v2/index")['ElTableV2']>
  'LazyElTabs': LazyComponent<typeof import("../../node_modules/element-plus/es/components/tabs/index")['ElTabs']>
  'LazyElTag': LazyComponent<typeof import("../../node_modules/element-plus/es/components/tag/index")['ElTag']>
  'LazyElOption': LazyComponent<typeof import("../../node_modules/element-plus/es/components/select/index")['ElOption']>
  'LazyElTimeSelect': LazyComponent<typeof import("../../node_modules/element-plus/es/components/time-select/index")['ElTimeSelect']>
  'LazyElOverlay': LazyComponent<typeof import("../../node_modules/element-plus/es/components/overlay/index")['ElOverlay']>
  'LazyElTimeline': LazyComponent<typeof import("../../node_modules/element-plus/es/components/timeline/index")['ElTimeline']>
  'LazyElOptionGroup': LazyComponent<typeof import("../../node_modules/element-plus/es/components/select/index")['ElOptionGroup']>
  'LazyElPageHeader': LazyComponent<typeof import("../../node_modules/element-plus/es/components/page-header/index")['ElPageHeader']>
  'LazyElTooltip': LazyComponent<typeof import("../../node_modules/element-plus/es/components/tooltip/index")['ElTooltip']>
  'LazyElTimelineItem': LazyComponent<typeof import("../../node_modules/element-plus/es/components/timeline/index")['ElTimelineItem']>
  'LazyElTour': LazyComponent<typeof import("../../node_modules/element-plus/es/components/tour/index")['ElTour']>
  'LazyElTransfer': LazyComponent<typeof import("../../node_modules/element-plus/es/components/transfer/index")['ElTransfer']>
  'LazyElTourStep': LazyComponent<typeof import("../../node_modules/element-plus/es/components/tour/index")['ElTourStep']>
  'LazyElTree': LazyComponent<typeof import("../../node_modules/element-plus/es/components/tree/index")['ElTree']>
  'LazyElIconAddLocation': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['AddLocation']>
  'LazyElTreeV2': LazyComponent<typeof import("../../node_modules/element-plus/es/components/tree-v2/index")['ElTreeV2']>
  'LazyElIconAim': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Aim']>
  'LazyElTreeSelect': LazyComponent<typeof import("../../node_modules/element-plus/es/components/tree-select/index")['ElTreeSelect']>
  'LazyElUpload': LazyComponent<typeof import("../../node_modules/element-plus/es/components/upload/index")['ElUpload']>
  'LazyElIconAlarmClock': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['AlarmClock']>
  'LazyElIconArrowDown': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowDown']>
  'LazyElIconArrowDownBold': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowDownBold']>
  'LazyElIconApple': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Apple']>
  'LazyElIconArrowLeft': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowLeft']>
  'LazyElIconArrowRight': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowRight']>
  'LazyElIconArrowUp': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowUp']>
  'LazyElIconArrowLeftBold': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowLeftBold']>
  'LazyElIconArrowRightBold': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowRightBold']>
  'LazyElIconAvatar': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Avatar']>
  'LazyElIconBack': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Back']>
  'LazyElIconArrowUpBold': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ArrowUpBold']>
  'LazyElTimePicker': LazyComponent<typeof import("../../node_modules/element-plus/es/components/time-picker/index")['ElTimePicker']>
  'LazyElIconBasketball': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Basketball']>
  'LazyElIconBaseball': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Baseball']>
  'LazyElIconBell': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Bell']>
  'LazyElText': LazyComponent<typeof import("../../node_modules/element-plus/es/components/text/index")['ElText']>
  'LazyElIconBellFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['BellFilled']>
  'LazyElIconBottom': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Bottom']>
  'LazyElWatermark': LazyComponent<typeof import("../../node_modules/element-plus/es/components/watermark/index")['ElWatermark']>
  'LazyElPopconfirm': LazyComponent<typeof import("../../node_modules/element-plus/es/components/popconfirm/index")['ElPopconfirm']>
  'LazyElIconBicycle': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Bicycle']>
  'LazyElIconBox': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Box']>
  'LazyElIconBottomLeft': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['BottomLeft']>
  'LazyElIconBrush': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Brush']>
  'LazyElIconCalendar': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Calendar']>
  'LazyElIconBriefcase': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Briefcase']>
  'LazyElIconCamera': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Camera']>
  'LazyElIconBrushFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['BrushFilled']>
  'LazyElIconCaretLeft': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CaretLeft']>
  'LazyElIconCaretBottom': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CaretBottom']>
  'LazyElIconCaretTop': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CaretTop']>
  'LazyElIconCaretRight': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CaretRight']>
  'LazyElIconCameraFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CameraFilled']>
  'LazyElIconCellphone': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Cellphone']>
  'LazyElIconChatDotRound': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChatDotRound']>
  'LazyElIconBottomRight': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['BottomRight']>
  'LazyElIconChatLineRound': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChatLineRound']>
  'LazyElIconBowl': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Bowl']>
  'LazyElIconBurger': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Burger']>
  'LazyElIconChatLineSquare': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChatLineSquare']>
  'LazyElIconChatRound': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChatRound']>
  'LazyElIconChecked': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Checked']>
  'LazyElIconCheck': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Check']>
  'LazyElIconChatDotSquare': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChatDotSquare']>
  'LazyElIconCherry': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Cherry']>
  'LazyElIconCircleCheck': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CircleCheck']>
  'LazyElIconChromeFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChromeFilled']>
  'LazyElIconChatSquare': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ChatSquare']>
  'LazyElIconCirclePlusFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CirclePlusFilled']>
  'LazyElIconChicken': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Chicken']>
  'LazyElIconCircleCloseFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CircleCloseFilled']>
  'LazyElIconCloudy': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Cloudy']>
  'LazyElIconClock': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Clock']>
  'LazyElIconClose': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Close']>
  'LazyElIconCloseBold': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CloseBold']>
  'LazyElIconCoffee': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Coffee']>
  'LazyElIconCoffeeCup': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CoffeeCup']>
  'LazyElIconCoin': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Coin']>
  'LazyElIconColdDrink': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ColdDrink']>
  'LazyElIconCollectionTag': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CollectionTag']>
  'LazyElIconCompass': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Compass']>
  'LazyElIconCollection': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Collection']>
  'LazyElIconComment': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Comment']>
  'LazyElIconConnection': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Connection']>
  'LazyElIconCopyDocument': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CopyDocument']>
  'LazyElIconCoordinate': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Coordinate']>
  'LazyElIconCircleCheckFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CircleCheckFilled']>
  'LazyElIconCircleClose': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CircleClose']>
  'LazyElIconCirclePlus': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CirclePlus']>
  'LazyElIconCreditCard': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['CreditCard']>
  'LazyElIconCpu': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Cpu']>
  'LazyElIconDArrowRight': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DArrowRight']>
  'LazyElIconCrop': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Crop']>
  'LazyElIconDCaret': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DCaret']>
  'LazyElIconDelete': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Delete']>
  'LazyElIconDataBoard': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DataBoard']>
  'LazyElIconDataLine': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DataLine']>
  'LazyElIconDArrowLeft': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DArrowLeft']>
  'LazyElIconDataAnalysis': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DataAnalysis']>
  'LazyElIconDeleteFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DeleteFilled']>
  'LazyElIconDiscount': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Discount']>
  'LazyElIconDessert': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Dessert']>
  'LazyElIconDeleteLocation': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DeleteLocation']>
  'LazyElIconDishDot': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DishDot']>
  'LazyElIconDish': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Dish']>
  'LazyElIconDocument': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Document']>
  'LazyElIconDocumentAdd': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DocumentAdd']>
  'LazyElIconDocumentChecked': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DocumentChecked']>
  'LazyElIconDocumentCopy': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DocumentCopy']>
  'LazyElIconDocumentDelete': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DocumentDelete']>
  'LazyElIconDocumentRemove': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['DocumentRemove']>
  'LazyElIconDownload': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Download']>
  'LazyElIconDrizzling': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Drizzling']>
  'LazyElIconEdit': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Edit']>
  'LazyElIconEditPen': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['EditPen']>
  'LazyElIconEleme': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Eleme']>
  'LazyElIconElementPlus': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ElementPlus']>
  'LazyElIconElemeFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ElemeFilled']>
  'LazyElIconFailed': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Failed']>
  'LazyElIconFemale': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Female']>
  'LazyElIconExpand': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Expand']>
  'LazyElIconFilter': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Filter']>
  'LazyElIconFinished': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Finished']>
  'LazyElIconFilm': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Film']>
  'LazyElIconFiles': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Files']>
  'LazyElIconFirstAidKit': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FirstAidKit']>
  'LazyElIconFold': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Fold']>
  'LazyElIconFlag': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Flag']>
  'LazyElIconFolderAdd': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FolderAdd']>
  'LazyElIconFolderChecked': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FolderChecked']>
  'LazyElIconFolderDelete': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FolderDelete']>
  'LazyElIconFolderOpened': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FolderOpened']>
  'LazyElIconFolder': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Folder']>
  'LazyElIconFolderRemove': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FolderRemove']>
  'LazyElIconFood': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Food']>
  'LazyElIconFootball': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Football']>
  'LazyElIconForkSpoon': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ForkSpoon']>
  'LazyElIconFries': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Fries']>
  'LazyElIconFullScreen': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['FullScreen']>
  'LazyElIconGoblet': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Goblet']>
  'LazyElIconGobletFull': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['GobletFull']>
  'LazyElIconGobletSquare': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['GobletSquare']>
  'LazyElIconGobletSquareFull': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['GobletSquareFull']>
  'LazyElIconGoldMedal': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['GoldMedal']>
  'LazyElIconGoodsFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['GoodsFilled']>
  'LazyElIconGrape': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Grape']>
  'LazyElIconGoods': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Goods']>
  'LazyElIconGrid': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Grid']>
  'LazyElIconHandbag': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Handbag']>
  'LazyElIconGuide': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Guide']>
  'LazyElIconHeadset': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Headset']>
  'LazyElIconHelp': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Help']>
  'LazyElIconHide': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Hide']>
  'LazyElIconHelpFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['HelpFilled']>
  'LazyElIconHistogram': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Histogram']>
  'LazyElIconHomeFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['HomeFilled']>
  'LazyElIconHouse': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['House']>
  'LazyElIconHotWater': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['HotWater']>
  'LazyElIconIceCream': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['IceCream']>
  'LazyElIconIceCreamSquare': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['IceCreamSquare']>
  'LazyElIconIceCreamRound': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['IceCreamRound']>
  'LazyElIconIceDrink': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['IceDrink']>
  'LazyElIconIceTea': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['IceTea']>
  'LazyElIconInfoFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['InfoFilled']>
  'LazyElIconIphone': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Iphone']>
  'LazyElIconKey': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Key']>
  'LazyElIconKnifeFork': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['KnifeFork']>
  'LazyElIconLightning': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Lightning']>
  'LazyElIconList': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['List']>
  'LazyElIconLink': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Link']>
  'LazyElIconLoading': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Loading']>
  'LazyElIconLocation': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Location']>
  'LazyElIconLocationFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['LocationFilled']>
  'LazyElIconLocationInformation': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['LocationInformation']>
  'LazyElIconLock': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Lock']>
  'LazyElIconLollipop': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Lollipop']>
  'LazyElIconMagicStick': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MagicStick']>
  'LazyElIconMagnet': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Magnet']>
  'LazyElIconMale': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Male']>
  'LazyElIconManagement': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Management']>
  'LazyElIconMapLocation': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MapLocation']>
  'LazyElIconMedal': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Medal']>
  'LazyElIconMemo': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Memo']>
  'LazyElIconMenu': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Menu']>
  'LazyElIconMessage': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Message']>
  'LazyElIconMessageBox': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MessageBox']>
  'LazyElIconMic': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Mic']>
  'LazyElIconMicrophone': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Microphone']>
  'LazyElIconMilkTea': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MilkTea']>
  'LazyElIconMinus': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Minus']>
  'LazyElIconMonitor': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Monitor']>
  'LazyElIconMoney': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Money']>
  'LazyElIconMoon': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Moon']>
  'LazyElIconMoonNight': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MoonNight']>
  'LazyElIconMore': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['More']>
  'LazyElIconMostlyCloudy': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MostlyCloudy']>
  'LazyElIconMouse': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Mouse']>
  'LazyElIconMoreFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MoreFilled']>
  'LazyElIconMute': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Mute']>
  'LazyElIconMuteNotification': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['MuteNotification']>
  'LazyElIconMug': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Mug']>
  'LazyElIconNoSmoking': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['NoSmoking']>
  'LazyElIconNotebook': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Notebook']>
  'LazyElIconOfficeBuilding': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['OfficeBuilding']>
  'LazyElIconNotification': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Notification']>
  'LazyElIconOdometer': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Odometer']>
  'LazyElIconOpen': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Open']>
  'LazyElIconOpportunity': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Opportunity']>
  'LazyElIconOperation': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Operation']>
  'LazyElIconOrange': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Orange']>
  'LazyElIconPaperclip': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Paperclip']>
  'LazyElIconPear': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Pear']>
  'LazyElIconPhone': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Phone']>
  'LazyElIconPhoneFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['PhoneFilled']>
  'LazyElIconPicture': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Picture']>
  'LazyElIconPictureFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['PictureFilled']>
  'LazyElIconPictureRounded': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['PictureRounded']>
  'LazyElIconPieChart': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['PieChart']>
  'LazyElIconPlace': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Place']>
  'LazyElIconPartlyCloudy': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['PartlyCloudy']>
  'LazyElIconPlatform': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Platform']>
  'LazyElIconPlus': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Plus']>
  'LazyElIconPointer': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Pointer']>
  'LazyElIconPosition': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Position']>
  'LazyElIconPostcard': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Postcard']>
  'LazyElIconPresent': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Present']>
  'LazyElIconPrinter': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Printer']>
  'LazyElIconPouring': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Pouring']>
  'LazyElIconQuartzWatch': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['QuartzWatch']>
  'LazyElIconRank': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Rank']>
  'LazyElIconQuestionFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['QuestionFilled']>
  'LazyElIconPromotion': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Promotion']>
  'LazyElIconPriceTag': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['PriceTag']>
  'LazyElIconReading': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Reading']>
  'LazyElIconRefresh': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Refresh']>
  'LazyElIconRefreshLeft': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['RefreshLeft']>
  'LazyElIconRefrigerator': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Refrigerator']>
  'LazyElIconRemove': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Remove']>
  'LazyElIconRefreshRight': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['RefreshRight']>
  'LazyElIconRight': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Right']>
  'LazyElIconReadingLamp': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ReadingLamp']>
  'LazyElIconSchool': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['School']>
  'LazyElIconRemoveFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['RemoveFilled']>
  'LazyElIconScissor': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Scissor']>
  'LazyElIconSelect': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Select']>
  'LazyElIconScaleToOriginal': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ScaleToOriginal']>
  'LazyElIconSell': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Sell']>
  'LazyElIconSearch': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Search']>
  'LazyElIconSetUp': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SetUp']>
  'LazyElIconSemiSelect': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SemiSelect']>
  'LazyElIconService': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Service']>
  'LazyElIconShare': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Share']>
  'LazyElIconSetting': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Setting']>
  'LazyElIconShip': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Ship']>
  'LazyElIconShoppingCart': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ShoppingCart']>
  'LazyElIconShop': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Shop']>
  'LazyElIconShoppingBag': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ShoppingBag']>
  'LazyElIconShoppingCartFull': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ShoppingCartFull']>
  'LazyElIconShoppingTrolley': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ShoppingTrolley']>
  'LazyElIconSoldOut': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SoldOut']>
  'LazyElIconSmoking': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Smoking']>
  'LazyElIconSoccer': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Soccer']>
  'LazyElIconSort': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Sort']>
  'LazyElIconSortDown': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SortDown']>
  'LazyElIconStar': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Star']>
  'LazyElIconStarFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['StarFilled']>
  'LazyElIconSortUp': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SortUp']>
  'LazyElIconStopwatch': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Stopwatch']>
  'LazyElIconSuitcase': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Suitcase']>
  'LazyElIconSuccessFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SuccessFilled']>
  'LazyElIconSugar': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Sugar']>
  'LazyElIconSunny': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Sunny']>
  'LazyElIconSunset': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Sunset']>
  'LazyElIconSwitch': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Switch']>
  'LazyElIconSuitcaseLine': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SuitcaseLine']>
  'LazyElIconSunrise': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Sunrise']>
  'LazyElIconSwitchButton': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SwitchButton']>
  'LazyElIconTicket': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Ticket']>
  'LazyElIconSwitchFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['SwitchFilled']>
  'LazyElIconTimer': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Timer']>
  'LazyElIconTakeawayBox': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['TakeawayBox']>
  'LazyElIconTools': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Tools']>
  'LazyElIconTop': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Top']>
  'LazyElIconTopLeft': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['TopLeft']>
  'LazyElIconTopRight': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['TopRight']>
  'LazyElIconTickets': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Tickets']>
  'LazyElIconToiletPaper': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ToiletPaper']>
  'LazyElIconTrophyBase': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['TrophyBase']>
  'LazyElIconTurnOff': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['TurnOff']>
  'LazyElIconUmbrella': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Umbrella']>
  'LazyElIconTrendCharts': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['TrendCharts']>
  'LazyElIconUpload': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Upload']>
  'LazyElIconTrophy': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Trophy']>
  'LazyElIconUnlock': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Unlock']>
  'LazyElIconUploadFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['UploadFilled']>
  'LazyElIconStamp': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Stamp']>
  'LazyElIconUser': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['User']>
  'LazyElIconUserFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['UserFilled']>
  'LazyElIconVan': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Van']>
  'LazyElIconVideoCamera': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['VideoCamera']>
  'LazyElIconVideoCameraFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['VideoCameraFilled']>
  'LazyElIconVideoPause': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['VideoPause']>
  'LazyElIconVideoPlay': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['VideoPlay']>
  'LazyElIconView': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['View']>
  'LazyElIconWalletFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['WalletFilled']>
  'LazyElIconWallet': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Wallet']>
  'LazyElIconWarning': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Warning']>
  'LazyElIconWarnTriangleFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['WarnTriangleFilled']>
  'LazyElIconWatermelon': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Watermelon']>
  'LazyElIconWatch': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['Watch']>
  'LazyElIconZoomIn': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ZoomIn']>
  'LazyElIconWarningFilled': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['WarningFilled']>
  'LazyElIconWindPower': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['WindPower']>
  'LazyElIconZoomOut': LazyComponent<typeof import("../../node_modules/@element-plus/icons-vue/dist/index")['ZoomOut']>
  'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
