// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/2/9 16:57:24
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["D:/桌面/biyesheji/vitae-vue2.0/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/桌面/biyesheji/vitae-vue2.0/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/桌面/biyesheji/vitae-vue2.0/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/桌面/biyesheji/vitae-vue2.0/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/桌面/biyesheji/vitae-vue2.0/plugins/**/*.{js,ts,mjs}","D:/桌面/biyesheji/vitae-vue2.0/composables/**/*.{js,ts,mjs}","D:/桌面/biyesheji/vitae-vue2.0/utils/**/*.{js,ts,mjs}","D:/桌面/biyesheji/vitae-vue2.0/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/桌面/biyesheji/vitae-vue2.0/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/桌面/biyesheji/vitae-vue2.0/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/桌面/biyesheji/vitae-vue2.0/app.config.{js,ts,mjs}","D:/桌面/biyesheji/vitae-vue2.0/app/spa-loading-template.html"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;