// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/11/9 15:34:03
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["D:/桌面/biyesheji/nuxt3-starter-ts-full/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/桌面/biyesheji/nuxt3-starter-ts-full/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/桌面/biyesheji/nuxt3-starter-ts-full/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/桌面/biyesheji/nuxt3-starter-ts-full/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/桌面/biyesheji/nuxt3-starter-ts-full/plugins/**/*.{js,ts,mjs}","D:/桌面/biyesheji/nuxt3-starter-ts-full/composables/**/*.{js,ts,mjs}","D:/桌面/biyesheji/nuxt3-starter-ts-full/utils/**/*.{js,ts,mjs}","D:/桌面/biyesheji/nuxt3-starter-ts-full/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/桌面/biyesheji/nuxt3-starter-ts-full/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/桌面/biyesheji/nuxt3-starter-ts-full/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/桌面/biyesheji/nuxt3-starter-ts-full/app.config.{js,ts,mjs}","D:/桌面/biyesheji/nuxt3-starter-ts-full/app/spa-loading-template.html"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;